### ISSUE TITLE
Unable to consume github-trending api

### ISSUE THREAD

**Issue by anshudaur** [devdigital/github-trendy#1]
Error: Cannot find module 'github-trends'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by devdigital** [comment]
Hi, sorry the README was a bit outdated - I have published an updated version if you'd like to try again - the package is called _github-trendy_.
